language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  
before_install:
  - cp uap-core/regexes.yaml ua_parser/regexes.yaml

install:
  - pip install .

script:
  - python ua_parser/user_agent_parser_test.py