sudo: false
language: python
python:
  - "3.5"

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py31
  - TOX_ENV=py32
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pypy
  - TOX_ENV=docs
  - TOX_ENV=pep8
  - TOX_ENV=py3pep8

install:
   - pip install tox

script:
   - tox -e $TOX_ENV
